AWSTemplateFormatVersion: "2010-09-09"
Description: Pass user Data with EC2 instace

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: this will get availaibyt zone of account

Resources:
  # Add Session Manager Access Role to EC2
  SsmIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal: 
              Service: [ ec2.amazonaws.com ]
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  # Create InstaceProfile
  ServerInstacneProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SsmIamRole
      Path: /

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for SSH and Port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 80
          FromPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: UserDataWithEc2

  # Create Elastic IP
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2UserDataInstance
      Tags:
        - Key: Name
          Value: UserDataWithEc2

  # EC2 Machine
  EC2UserDataInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      IamInstanceProfile: !Ref ServerInstacneProfile
      SecurityGroups:
        - !Ref ServerSecurityGroup
      Tags:
        - Key: Name
          Value: UserDataWithEc2

      # Install userData for starting Httpd
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello World from user data Stack: ${AWS::StackId}  Region: ${AWS::Region} " > /var/www/html/index.html
Outputs:
  PublicIp:
    Value:
      Fn::GetAtt:
        - EC2UserDataInstance
        - PublicIp
    Description: Get Public IP of Instance
